"""
verification/report_export.py

Generates a downloadable PDF of a verification report, and a plain-text
summary suitable for sharing (email, copy-paste, WhatsApp, etc).

USAGE:
    from verification.report_export import generate_pdf_report, generate_share_text
    pdf_bytes = generate_pdf_report(batch, herd, meat, outcome)
    text = generate_share_text(batch, herd, meat, outcome)
"""

from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_pdf_report(batch, herd, meat, outcome, batch_id: str) -> bytes:
    """
    Builds a one-page PDF summarising a batch's verification report.
    batch, herd, meat are sqlite3.Row objects; outcome is the dict returned
    by verification_engine.run_verification().
    Returns the PDF as raw bytes, ready for st.download_button.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], fontSize=18)
    heading_style = ParagraphStyle("HeadingStyle", parent=styles["Heading2"], spaceBefore=12)
    normal = styles["Normal"]

    story = []
    story.append(Paragraph("BeefLink Verification Report", title_style))
    story.append(Paragraph(f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}", normal))
    story.append(Spacer(1, 10 * mm))

    story.append(Paragraph(f"Batch ID: {batch_id}", heading_style))
    story.append(Paragraph(f"Farm: {batch['farm_id']}", normal))
    story.append(Paragraph(f"Date: {batch['date']}", normal))
    story.append(Spacer(1, 6 * mm))

    # Trust score summary table
    decision_color = {
        "Verified": colors.HexColor("#1D9E75"),
        "Review Required": colors.HexColor("#BA7517"),
        "Rejected": colors.HexColor("#A32D2D"),
    }.get(outcome["final_decision"], colors.black)

    story.append(Paragraph("Trust Score", heading_style))
    score_table = Table([
        ["Trust score", f"{outcome['trust_score']} / 100"],
        ["Final decision", outcome["final_decision"]],
    ], colWidths=[60 * mm, 100 * mm])
    score_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("TEXTCOLOR", (1, 1), (1, 1), decision_color),
        ("FONTNAME", (1, 1), (1, 1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Trust score breakdown", heading_style))
    breakdown_rows = [["Component", "Points earned"]]
    for component, points in outcome["trust_score_breakdown"].items():
        breakdown_rows.append([component.replace("_", " ").title(), f"{points['earned']} / {points['max']}"])
    breakdown_table = Table(breakdown_rows, colWidths=[80 * mm, 80 * mm])
    breakdown_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1EFE8")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(breakdown_table)
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Herd Verification", heading_style))
    story.append(Paragraph(f"Declared count: {batch['declared_count']}", normal))
    story.append(Paragraph(f"Detected count: {herd['detected_count']}", normal))
    story.append(Paragraph(f"Average detection confidence: {herd['average_confidence']*100:.1f}%", normal))
    story.append(Paragraph(f"Status: {herd['status']}", normal))
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Meat Freshness Verification", heading_style))
    story.append(Paragraph(f"Predicted label: {meat['freshness_label']}", normal))
    story.append(Paragraph(f"Confidence: {meat['freshness_confidence']*100:.1f}%", normal))
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Comparison", heading_style))
    story.append(Paragraph(f"Rule-based decision (fixed thresholds): {outcome['rule_based_decision']}", normal))
    story.append(Paragraph(
        "This report was generated by the BeefLink computer vision verification layer. "
        "It combines an independent herd count check and an independent meat freshness "
        "check into a single trust score, so a buyer can assess a supply listing without "
        "requiring a prior relationship with the farmer.", normal))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def generate_share_text(batch, herd, meat, outcome, batch_id: str) -> str:
    """Returns a short plain-text summary suitable for copy/paste or email."""
    return f"""BeefLink Verification Report — {batch_id}

Farm: {batch['farm_id']}
Date: {batch['date']}

TRUST SCORE: {outcome['trust_score']}/100 — {outcome['final_decision']}

Herd verification: declared {batch['declared_count']}, detected {herd['detected_count']} \
({herd['average_confidence']*100:.1f}% avg. confidence) — {herd['status']}
Meat freshness: {meat['freshness_label']} ({meat['freshness_confidence']*100:.1f}% confidence)

(Comparison) Rule-based decision: {outcome['rule_based_decision']}

Generated by BeefLink — an independent computer vision verification layer for organic beef supply listings.
""".strip()
